

/// FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const FETCH_FIREBASE_PROFILES = 'FETCH_FIREBASE_PROFILES';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';
export const FETCH_FIREBASE_USER_BIO = 'FETCH_FIREBASE_USER_BIO';
export const SAVE_FIREBASE_USER_BIO = 'SAVE_FIREBASE_USER_BIO';
export const FETCH_FIREBASE_TUTOR_INFO = 'FETCH_FIREBASE_TUTOR_INFO';
export const SAVE_FIREBASE_TUTOR_INFO = 'SAVE_FIREBASE_TUTOR_INFO';
export const FETCH_FIREBASE_IS_TUTOR = 'FETCH_FIREBASE_IS_TUTOR';
export const SAVE_FIREBASE_IS_TUTOR = 'SAVE_FIREBASE_IS_TUTOR';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_NEW_NOTIFICATION_NUMBER = 'FETCH_NEW_NOTIFICATION_NUMBER';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
